# Generated by Django 4.0.3 on 2022-03-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('trip_from', models.CharField(blank=True, max_length=50)),
                ('trip_to', models.CharField(blank=True, max_length=50)),
                ('receiver', models.CharField(blank=True, max_length=50)),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('date_created', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
