# Generated by Django 4.0.3 on 2022-03-23 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nestapp', '0002_rename_trips_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('county', models.CharField(choices=[('KSM', 'Kisumu'), ('NRB', 'Nairobi'), ('MSA', 'Mombasa')], default='NRB', max_length=3)),
                ('description', models.TextField()),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('date_created', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'location_point',
            },
        ),
        migrations.RemoveField(
            model_name='trip',
            name='receiver',
        ),
        migrations.AddField(
            model_name='trip',
            name='receiver_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trip_start', to='nestapp.location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_end', to='nestapp.location'),
        ),
    ]
