# Generated by Django 4.0.3 on 2022-03-23 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nestapp', '0004_alter_trip_receiver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_to',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='trip_end', to='nestapp.location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
