# Generated by Django 4.0.3 on 2022-03-30 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nestapp', '0005_alter_location_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestapp.location')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestapp.trip')),
            ],
        ),
    ]
